app_show_case_homepage:
    path:     /
    defaults: { _controller: AppShowCaseBundle:FrontOffice\Front:homePage}
    options:
        expose: true

app_show_case_contact:
    path:     /contact
    defaults: { _controller: AppShowCaseBundle:FrontOffice\Front:contact }
    options:
        expose: true

app_show_case_about:
    path:     /about
    defaults: { _controller: AppShowCaseBundle:FrontOffice\Front:about }

app_show_case_freelance:
  path:     /freelance
  defaults: { _controller: AppShowCaseBundle:FrontOffice\Front:freelance }

app_show_case_project:
  path:     /project/{pro}
  defaults: { _controller: AppShowCaseBundle:FrontOffice\Front:project, pro: false }

app_show_case_learning:
  path:     /learning
  defaults: { _controller: AppShowCaseBundle:FrontOffice\Front:learning}

app_show_case_admin_homepage:
  path:     /admin/home
  defaults: { _controller: AppShowCaseBundle:BackOffice\Admin:home }

projects_lists:
  path:     /projects/list
  defaults: { _controller: AppShowCaseBundle:FrontOffice\Front:getProjectsClientView }

mini_project:
  path:     /mini_projects/list
  defaults: { _controller: AppShowCaseBundle:FrontOffice\Front:miniProjectList }

app_show_login:
  path:     /login
  defaults: { _controller: AppShowCaseBundle:FrontOffice\Front:login }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



