app_show_case:
    resource: "@AppShowCaseBundle/Resources/config/routing.yml"
    prefix:   /
    #prefix:   /{_locale}

show_case_api:
    type:     rest
    prefix:   /api
    resource: "@AppShowCaseBundle/Controller/Api"

