<?php

namespace App\ShowCaseBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjectsQuery()
    {
        $qb = $this->createQueryBuilder('p');

        return $qb->getQuery();
    }
}
